version: '3'
services:
  db:
    image: redis:latest
    container_name: database
    expose:
      - 6379

  job-queue:
    image: rabbitmq:alpine
    container_name: job-queue
    expose:
      - 5672

  app:
    build: ./webserver
    environment:
      - FILE_STORE=/app/media
      - PORT=3000
      - REDIS_DB_URL=redis://database
      - JOB_QUEUE_URL=amqp://job-queue
      - TASK_QUEUE_NAME=task_queue
    restart: on-failure
    depends_on:
      - db
      - job-queue
    volumes:
      - storage:/app/media
    ports:
      - 5555:3000
    command:
      sh -c 'yarn start'

  worker:
    build: ./worker
    environment:
      - FILE_STORE=/app/data
      - JOB_QUEUE_URL=job-queue
      - TASK_QUEUE_NAME=task_queue
    restart: on-failure
    depends_on:
      - job-queue
    volumes:
      - storage:/app/data
    command:
      sh -c 'python worker.py'
volumes:
  storage:
